import fs from 'node:fs';

const read = (path) => fs.readFileSync(path, 'utf8');
const fail = (message) => { console.error(`VALIDATION FAILED: ${message}`); process.exitCode = 1; };
const expect = (condition, message) => { if (!condition) fail(message); };

const pkg = JSON.parse(read('package.json'));
const versionFile = read('VERSION').trim();
const app = read('src/App.jsx');
const main = read('src/main.jsx');
const music = read('src/music/MusicApp.tsx');
const musicCss = read('src/music/music.css');
const frxeIcon = read('public/frxe-icon.svg');
const searchApi = read('api/youtube-search.js');
const syncApi = read('api/github-sync.js');
const sharedMusic = read('src/shared/musicSearch.js');
const sourceContract = read('shared/source-contract.js');
const sourceAdapter = read('scripts/adapt-sources.mjs');
const sourceManifest = JSON.parse(read('src/generated/source-manifest.json'));
const playwright = read('playwright.config.js');
const e2e = read('tests/e2e/nont.spec.js');
const unit = read('tests/unit/musicSearch.test.mjs');
const sourceUnit = read('tests/unit/source-contract.test.mjs');
const ci = read('.github/workflows/ci.yml');
const adaptWorkflow = read('.github/workflows/adapt-sources.yml');
const vite = read('vite.config.js');
const vercel = read('vercel.json');
const index = read('index.html');
const polish = read('src/polish.css');

expect(pkg.version === versionFile, `package.json (${pkg.version}) and VERSION (${versionFile}) must match`);
expect(!fs.existsSync('api/search.js'), 'obsolete api/search.js must stay removed');
expect(!fs.existsSync('api/chat.js'), 'unused API-provider proxy must stay removed');
expect(!app.includes("'web-search'"), 'Web Search navigation must stay removed');
expect(!app.includes("page === 'updates'"), 'legacy Updates page must stay removed');
expect(!app.includes('voidnont/NONT-Nexus'), 'legacy NONT-Nexus repository reference must stay removed');

expect(sourceAdapter.includes("repo: 'voidnont/nont'"), 'nont.me source adapter must track voidnont/nont');
expect(sourceAdapter.includes("repo: 'voidnont/Frxe'"), 'music.nont.me source adapter must track voidnont/Frxe');
expect(!sourceAdapter.includes("repo: 'voidnont/NontHub'"), 'NontHub must not remain a website source-of-truth');
expect(!sourceAdapter.includes("repo: 'voidnont/NontMusic'"), 'NontMusic must not remain a website source-of-truth');
expect(sourceAdapter.includes("versionPath: 'app/build.gradle.kts'"), 'Frxe adapter must use the current repository layout');
expect(sourceAdapter.includes('patchNontWeb'), 'source adapter must map nont.me to voidnont/nont');
expect(sourceAdapter.includes('patchFrxeWeb'), 'source adapter must update the Frxe player source version');
expect(sourceAdapter.includes('patchFrxeApp'), 'source adapter must update the Frxe Hub card version');

const sourceKeys = Object.keys(sourceManifest).sort();
expect(JSON.stringify(sourceKeys) === JSON.stringify(['voidnont/Frxe', 'voidnont/nont']), 'generated manifest must contain only voidnont/nont and voidnont/Frxe');
expect(syncApi.includes("'voidnont/nont':"), 'GitHub sync API must allow voidnont/nont');
expect(syncApi.includes("'voidnont/frxe':"), 'GitHub sync API must allow voidnont/Frxe');
expect(!syncApi.includes("'voidnont/nonthub':"), 'GitHub sync API must stop using voidnont/NontHub as the nont.me source');
expect(syncApi.includes('voidnont/NontMusic'), 'desktop NontMusic downloads may remain available');
expect(syncApi.includes('voidnont/veilbrowser'), 'Veil desktop downloads must remain available');

expect(app.includes("['installer', 'Installer'"), 'Installer must remain in navigation');
expect(app.includes("setInstallerMode('install')"), 'Installer must retain Install mode');
expect(app.includes("setInstallerMode('update')"), 'Installer must retain Update mode');
expect(app.includes("const FRXE_WEB_VERSION = '"), 'Hub must expose a source-synced Frxe web version');
expect(app.includes("id: 'frxe-web', name: 'FRXE Web'"), 'Hub library must identify music.nont.me as FRXE Web');
expect(app.includes("iconUrl: '/frxe-icon.svg'"), 'Hub FRXE Web card must use Frxe branding');
expect(!app.includes("id: 'nontmusic-web'"), 'legacy NontMusic Web card must stay removed');
expect(music.includes('const FRXE_SOURCE_VERSION'), 'Frxe web player must expose its source version');
expect(music.includes('https://github.com/voidnont/Frxe'), 'Frxe web player must link to its source repository');
expect(music.includes("type FrxeTab = 'home' | 'search' | 'save' | 'library' | 'settings'"), 'Frxe web must keep the five source tabs');
expect(music.includes('../shared/musicSearch.js'), 'Frxe web search must use shared music search logic');
expect(music.includes('frxe-mini-player'), 'Frxe web must keep the liquid mini-player');
expect(music.includes('NOW PLAYING'), 'Frxe web must keep the full player');
expect(music.includes('Save direct media'), 'Frxe web must keep browser-safe Save');
expect(main.includes("document.title = 'FRXE'"), 'music.nont.me must identify as FRXE');
expect(main.includes('Open FRXE Web Player'), 'NontHub homepage must link to the FRXE web player');
expect(fs.existsSync('public/frxe-icon.svg'), 'Frxe favicon must exist');
expect(frxeIcon.includes('viewBox="0 0 108 108"'), 'Frxe web icon must keep the Android launcher viewport');
expect(frxeIcon.includes('fill="#09090B"') && frxeIcon.includes('M0,0h108v108h-108z'), 'Frxe web icon must keep the launcher background');
expect(frxeIcon.includes('fill="#FFFFFF"') && frxeIcon.includes('M25,27h36v10h-24v13h21v10h-21v21h-12z'), 'Frxe web icon must keep the launcher F mark');
expect(frxeIcon.includes('fill="#B7FF59"') && frxeIcon.includes('M63,47l8,-8l12,12l12,-12l8,8l-12,12l12,12l-8,8l-12,-12l-12,12l-8,-8l12,-12z'), 'Frxe web icon must keep the launcher X mark');
expect(musicCss.includes('.frxe-glass'), 'Frxe liquid-glass styling must remain');
expect(musicCss.includes('backdrop-filter'), 'Frxe glass must keep backdrop blur');
expect(musicCss.includes('prefers-reduced-motion'), 'Frxe web must retain reduced-motion support');
expect(searchApi.includes('../src/shared/musicSearch.js'), 'Music API must use shared music search logic');
expect(sharedMusic.includes('buildProviderMusicQuery'), 'shared music module must keep provider-intent logic');
expect(sharedMusic.includes('mergeAndRankMusicResults'), 'shared music module must keep duplicate merging/ranking');
expect(sharedMusic.includes('refineMusicMetadata'), 'shared music module must keep metadata cleanup');
expect(searchApi.includes('REQUEST_TIMEOUT_MS'), 'music search requests must retain a timeout');
expect(syncApi.includes('REQUEST_TIMEOUT_MS'), 'GitHub sync requests must retain a timeout');
expect(syncApi.includes('sourceAheadOfRelease'), 'source/release drift detection must remain enabled');
expect(sourceContract.includes("key.endsWith('/nont')"), 'source contract must understand voidnont/nont');
expect(sourceContract.includes("key.endsWith('/frxe')"), 'source contract must understand Frxe');
expect(sourceContract.includes("'app/src/main/java/com/frxe/music"), 'source contract must understand the current Frxe app layout');
expect(vite.includes('sync-nont-web-version'), 'Vite must keep displayed Hub version synced with package.json');
expect(main.includes("import('./polish.css')"), 'Hub corrective CSS must be loaded');
expect(polish.includes('repeat(5'), 'mobile Hub navigation must retain five columns');
expect(polish.includes('prefers-reduced-motion'), 'Hub must retain reduced-motion support');
expect(index.includes('<title>NontHub</title>'), 'public HTML title must stay NontHub');
expect(!index.includes('NONT Nexus'), 'legacy Nexus metadata must stay removed');
expect(vercel.includes('npm run check && npm run build'), 'Vercel must validate before building');
expect(vercel.includes('Content-Security-Policy'), 'production CSP header must remain configured');
expect(vercel.includes('X-Content-Type-Options'), 'content type hardening must remain configured');
expect(pkg.devDependencies?.['@playwright/test'], 'Playwright must remain installed');
expect(pkg.scripts?.['test:unit'], 'unit tests must remain runnable');
expect(pkg.scripts?.['test:e2e'], 'browser E2E tests must remain runnable');
expect(pkg.scripts?.['adapt:sources'], 'source adapter command must remain runnable');
expect(playwright.includes("testDir: './tests/e2e'"), 'Playwright must target the E2E suite');
expect(e2e.includes('Hub exposes Installer'), 'E2E suite must cover the Installer');
expect(e2e.includes('mobile Hub navigation contains exactly five'), 'E2E suite must cover mobile navigation');
expect(e2e.includes('Frxe web player mirrors'), 'E2E suite must cover the Frxe web player');
expect(unit.includes('duplicate versions collapse'), 'unit suite must cover duplicate merging');
expect(sourceUnit.includes('Nont contract follows voidnont/nont'), 'unit suite must cover the nont.me source mapping');
expect(sourceUnit.includes('Frxe contract follows'), 'unit suite must cover Frxe source adaptation');
expect(ci.includes('npm run test:unit'), 'CI must run unit tests');
expect(ci.includes('playwright install --with-deps chromium'), 'CI must install Chromium');
expect(ci.includes('npm run test:e2e:ci'), 'CI must run browser E2E tests');
expect(adaptWorkflow.includes("cron: '*/15 * * * *'"), 'source adapter must keep the 15-minute safety sync');
expect(adaptWorkflow.includes('Adapt website from Nont and Frxe'), 'source adapter workflow must identify the two source repositories');
expect(adaptWorkflow.includes('node scripts/adapt-sources.mjs'), 'source adapter workflow must run the adapter');

if (process.exitCode) process.exit(process.exitCode);
console.log(`Validation passed for nont.me v${pkg.version}.`);
